version: '3.9'

services:

  mongo_db:
    container_name: db_container
    image: mongo
    restart: always
    volumes:
      - mongo_db:/data/db
    command: mongod --quiet --logpath /dev/null
    
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - VITE_DB_URL=mongodb://mongo_db:27017/memedb
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}